name: intro-ia
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy==1.23.5
  - scikit-learn
  - ipykernel
  - seaborn
  - matplotlib
  - scipy
  - pyarrow
  - seaborn
  - ninja2
  - opencv-python
  - pytest